services:
  # Frontend Production service
  frontend:
    container_name: quran-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_PRIMARY_COLOR=${VITE_PRIMARY_COLOR}
        - VITE_PRIMARY_LIGHT=${VITE_PRIMARY_LIGHT}
        - VITE_PRIMARY_DARK=${VITE_PRIMARY_DARK}
        - VITE_SECONDARY_COLOR=${VITE_SECONDARY_COLOR}
        - VITE_BACKGROUND_COLOR=${VITE_BACKGROUND_COLOR}
        - VITE_PAPER_COLOR=${VITE_PAPER_COLOR}
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - quran-network
    restart: unless-stopped

networks:
  quran-network:
    driver: bridge
